{{- if and .Values.persistence.enabled .Values.persistence.hostPath -}}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "backend.fullname" . }}-pv
  labels:
    type: local
    {{- include "backend.labels" . | nindent 4 }}
spec:
  storageClassName: {{ .Values.persistence.storageClass | default "manual" }}
  capacity:
    storage: {{ .Values.persistence.size }}
  accessModes:
    - {{ .Values.persistence.accessMode }}
  hostPath:
    path: {{ .Values.persistence.hostPath }}
{{- end -}}
